# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - admint1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ecca53b024044a8a64ab067b11f4b32 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ac75c5466a7c4c65b21e98e7616184cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0ecca53b024044a8a64ab067b11f4b32 }}/admint1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'admint1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77543081c07a4e0eac89aea12a34bfd0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0ecca53b024044a8a64ab067b11f4b32 }}/admint1:${{ github.sha }}'