# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wbdservicet1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_4593d894059b45f1a3dbd9c8c1106465 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_22029dfeef244cbba4adb09d306ae1e0 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4593d894059b45f1a3dbd9c8c1106465 }}/wbd1:${{ github.sha }}
          file: ./Dockerfile
          env: DockerDBID=${{secrets.DOCKERDBID}}
          build-args: |
            DockerDBID=${{secrets.DOCKERDBID}}
            cloudinaryCloudName=${{secrets.CLOUDINARYCLOUDNAME}}
            cloudinaryApiKey=${{secrets.CLOUDINARYAPIKEY}}
            cloudinaryApiSecret=${{secrets.CLOUDINARYAPISECRET}}
            secretKey=${{secrets.SECRETKEY}}
            redisPassword=${{secrets.REDISPASSWORD}}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          port: 5000
          DockerDBID: ${{secrets.DOCKERDBID}}
          cloudinaryCloudName: ${{secrets.CLOUDINARYCLOUDNAME}}
          cloudinaryApiKey: ${{secrets.CLOUDINARYAPIKEY}}
          cloudinaryApiSecret: ${{secrets.CLOUDINARYAPISECRET}}
          secretKey: ${{secrets.SECRETKEY}}
          redisPassword: ${{secrets.REDISPASSWORD}}
          newKey: 12
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "wbdservicet1"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a94690508184d8281cfa2f1fc50753c }}
          images: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4593d894059b45f1a3dbd9c8c1106465 }}/wbd1:${{ github.sha }}"
